-- Create executives table for CEO directory
CREATE TABLE public.executives (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT 'Chief Executive Officer',
  company_id UUID REFERENCES public.companies(id) ON DELETE SET NULL,
  company_name TEXT NOT NULL,
  stock_symbol TEXT,
  bio TEXT,
  photo_url TEXT,
  region TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  linkedin_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.executives ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Anyone can view executives" ON public.executives
  FOR SELECT USING (true);

CREATE POLICY "Editors can manage executives" ON public.executives
  FOR ALL USING (
    has_role(auth.uid(), 'admin'::app_role) OR 
    has_role(auth.uid(), 'editor'::app_role)
  );

-- Update trigger
CREATE TRIGGER update_executives_updated_at
  BEFORE UPDATE ON public.executives
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Seed all 37 CEOs
INSERT INTO public.executives (name, title, company_name, stock_symbol, bio, region, slug) VALUES
-- AMERICAS (18)
('David B. Burritt', 'President and Chief Executive Officer', 'United States Steel Corporation', 'NYSE: X', 'David B. Burritt was appointed President and Chief Executive Officer of United States Steel Corporation in May 2017 and was named to the company''s Board of Directors. He joined U.S. Steel in September 2013 as Executive Vice President and Chief Financial Officer. Prior to joining U.S. Steel, Mr. Burritt served as Chief Financial Officer at Caterpillar Inc. He earned a bachelor''s degree in accounting from Bradley University in 1977 and received an MBA from the University of Illinois in Champaign in 1990. Mr. Burritt serves on the board of directors for Lockheed Martin and the National Safety Council.', 'Americas', 'david-burritt'),

('Peter R. Matt', 'President and Chief Executive Officer', 'Commercial Metals Co.', 'NYSE: CMC', 'Peter R. Matt was appointed President and CEO of Commercial Metals Company in September 2023, succeeding Barbara R. Smith who served as CEO from 2017. He previously served as President beginning in April 2023 and has been a board member since June 2020. Before joining CMC, Matt served as Executive Vice President and Chief Financial Officer of Constellium SE, a global aluminum fabrication company. From 2015 to 2016, he was a managing partner for Tumpline Capital LLC. From 1985 to 2015, he held various leadership positions with Credit Suisse. Matt holds a Bachelor''s degree from Amherst College and brings extensive financial, strategic and executive leadership experience to the role.', 'Americas', 'peter-matt'),

('Leon J. Topalian', 'Chair, President and Chief Executive Officer', 'Nucor Corporation', 'NYSE: NUE', 'Leon J. Topalian was named Chair, President and Chief Executive Officer of Nucor Corporation in 2022, after serving as President and CEO beginning in January 2020. He began his career with Nucor as a Project Engineer at Nucor Steel Berkeley in 1996 and was promoted to Cold Mill production supervisor in 1998. He has held various leadership positions throughout his nearly 30-year Nucor career in Australia, at Nucor Steel South Carolina, Nucor Steel Kankakee, and Nucor-Yamato Steel Co. Topalian served as Executive Vice President of Beam and Plate Products from 2017 to 2019. He earned a bachelor''s degree in marine engineering from Massachusetts Maritime Academy. He serves as Chairman of the World Steel Association''s Executive Board of Directors.', 'Americas', 'leon-topalian'),

('Jose Bayardo', 'Chairman, President and Chief Executive Officer', 'National Oilwell Varco (NOV Inc.)', 'NYSE: NOV', 'Jose Bayardo was appointed Chairman, President and Chief Executive Officer of NOV Inc., effective January 1, 2026, succeeding Clay C. Williams who led the company for over a decade. Bayardo previously served as President and Chief Operating Officer at NOV. His appointment was announced in November 2025 as part of NOV''s long-standing succession planning process. Clay Williams took over as CEO in 2014, succeeding Pete Miller.', 'Americas', 'jose-bayardo'),

('Lorenzo Simonelli', 'Chairman and Chief Executive Officer', 'Baker Hughes Company', 'Nasdaq: BKR', 'Lorenzo Simonelli is Chairman and CEO of Baker Hughes, an energy technology company. He was named Chairman of the Board in October 2017 and has been President and CEO since the Company''s creation in 2017, where he oversaw the successful merger of GE Oil & Gas with Baker Hughes Inc. Originally from Tuscany, Italy, Simonelli is a Business & Economics Graduate from Cardiff University in South Wales. He joined GE''s Financial Management Program in 1994 and held various positions including President & CEO of GE Transportation (2008-2013) and President & CEO of GE Oil & Gas (2013-2017). He currently serves on the Board of Iveco Group N.V. and resides in Houston.', 'Americas', 'lorenzo-simonelli'),

('Jeffrey A. Miller', 'Chairman, President and Chief Executive Officer', 'Halliburton Company', 'NYSE: HAL', 'Jeffrey A. Miller is Chairman, President and CEO of Halliburton. He has served on the Board since 2014, was President and Chief Health, Safety and Environment Officer from 2014–2017, CEO from 2017–2018, and has held the combined Chairman, President and CEO roles since January 2019. Born in Dallas, Texas in 1964, Miller earned his MBA from Texas A&M University. After working as a certified public accountant at Arthur Andersen, he joined Halliburton in 1997. During his career at Halliburton, he worked in oil field operations in Venezuela, Angola, Indonesia, and Dubai before moving to Houston in 2010 for executive roles. He became Executive Vice President and COO before assuming the presidency in 2014.', 'Americas', 'jeffrey-miller'),

('Olivier Le Peuch', 'Chief Executive Officer', 'Schlumberger Ltd. (SLB)', 'NYSE: SLB', 'Olivier Le Peuch is Chief Executive Officer of SLB (formerly Schlumberger), a position he has held since August 2019. A career engineer with deep tech expertise, Le Peuch brought a bold mandate to simplify, digitize, and reposition the company. Previously, he served as Chief Operating Officer and held various global management roles including Executive Vice President of Reservoir & Infrastructure, President of the Cameron Group, President of Schlumberger Completions, Vice President of Engineering, Manufacturing, and Sustaining, and President of Schlumberger Information Solutions. Under his leadership, SLB has launched the New Energies division (2020), rebranded from Schlumberger to SLB (2022), and is embedding AI across operations with platforms like DELFI and Lumi.', 'Americas', 'olivier-le-peuch'),

('Girish K. Saligram', 'President and Chief Executive Officer', 'Weatherford International plc', 'Nasdaq: WFRD', 'Girish K. Saligram has been President, Chief Executive Officer and Director at Weatherford International plc since October 12, 2020. Prior to joining Weatherford, he served as Chief Operating Officer of Exterran Corporation, and previously served as President, Global Services, after joining Exterran in 2016. Saligram also spent 20 years with GE in positions of increasing responsibility. He has over 28 years of international experience across multiple industries with a deep understanding of the oil and gas sector. Under his leadership, Weatherford has focused on operational excellence and financial performance after emerging from bankruptcy.', 'Americas', 'girish-saligram'),

('Anthony G. Petrello', 'Chairman, President and Chief Executive Officer', 'Nabors Industries Ltd.', 'NYSE: NBR', 'Anthony G. Petrello has served as Chairman of the Board of Nabors Industries since 2012 and as a director since 1991. He has been President and CEO of Nabors since October 2011, and previously served as President and Chief Operating Officer from 1991 to 2011, and Deputy Chairman from 2003 to 2012. Petrello joined Nabors in 1991 after working as a Partner at Baker McKenzie law firm from 1984 to 1991. He has played a significant role in the development of Nabors Industries from its formation. He serves as a director of Stewart & Stevenson LLC and of Hilcorp Energy Company, and is a member of the Board of Trustees of Texas Children''s Hospital.', 'Americas', 'anthony-petrello'),

('William Andrew Hendricks Jr.', 'President and Chief Executive Officer', 'Patterson-UTI Energy, Inc.', 'Nasdaq: PTEN', 'Andy Hendricks has served as President and Chief Executive Officer of Patterson-UTI since October 2012 and as a director since June 2017. He began his career with Patterson-UTI in 1987 as a drilling engineer and has held a variety of positions within the company in operations, management, and leadership. Under his leadership, Patterson-UTI has focused on transformation through technology, ESG initiatives, and reducing emissions on rigs. The company operates one of the largest fleets of land-based drilling rigs in North America and has led industry efforts in sustainability and capital discipline.', 'Americas', 'andy-hendricks'),

('Bernie Wolford Jr.', 'President and Chief Executive Officer', 'Diamond Offshore Drilling, Inc.', 'NYSE: DO', 'Bernie Wolford Jr. served as President and CEO of Diamond Offshore until the company was acquired by Noble Corporation in September 2024. Under his leadership, Diamond Offshore operated a fleet of offshore drilling rigs including four 7th generation drillships and high-spec semisubmersible rigs. Wolford stated that 2023 was a ''transformational year for Diamond Offshore'' as the company delivered strong operational results and positioned itself for the strategic merger with Noble. The acquisition was valued at approximately $1.6 billion and created a combined offshore drilling leader.', 'Americas', 'bernie-wolford'),

('Robert W. Eifler', 'President and Chief Executive Officer', 'Noble Corporation plc', 'NYSE: NE', 'Robert W. Eifler (age 45) has served as Noble Corporation''s President and CEO since May 2020 and as a director since 2020. He holds a B.S. in Systems & Information Engineering from the University of Virginia and an Acton MBA in Entrepreneurship. Eifler joined Noble in 2005 and held various operational and marketing roles, including Vice President & General Manager – Marketing & Contracts (2017-2019) and Senior Vice President, Commercial (2019-2020). Under his leadership, Noble completed the acquisition of Maersk Drilling in 2022 and Diamond Offshore in 2024, building one of the industry''s leading 7th-generation drillship fleets. He has led significant integration synergies and capital returns through buybacks and dividends.', 'Americas', 'robert-eifler'),

('Keelan Adamson', 'President and Chief Executive Officer', 'Transocean Ltd.', 'NYSE: RIG', 'Keelan Adamson is President and Chief Executive Officer of Transocean, appointed in February 2025 as part of a CEO succession plan. He previously served as President and Chief Operating Officer from February 2022, and before that as Executive Vice President and Chief Operations Officer (2018-2022). Adamson started his career as a drilling engineer with BP Exploration in 1991 and joined Transocean in July 1995. He has held multiple executive positions spanning Engineering and Technical Services, Major Capital Projects, Human Resources, Operations Integrity and HSE, as well as leadership roles in the U.K., Asia, Africa, and as Managing Director for operations in North America, Canada and Trinidad. He earned a bachelor''s degree in Aeronautical Engineering from The Queens University of Belfast in 1991.', 'Americas', 'keelan-adamson'),

('Simon William Johnson', 'President and Chief Executive Officer', 'Seadrill Limited', 'NYSE: SDRL', 'Simon William Johnson serves as President and Chief Executive Officer of Seadrill and was appointed to these roles in March 2022. Mr. Johnson has worked internationally for the past 28 years for several publicly listed offshore drilling contractors, including Seadrill, Diamond Offshore, Noble Corporation, and Borr Drilling. He brings extensive global offshore drilling experience across multiple regions and has expertise in operational management, commercial strategy, and business development. Johnson holds a bachelor''s degree in Finance and International Business. He emerged from Seadrill''s Chapter 11 bankruptcy reorganization in February 2022 and has led the company''s operational turnaround.', 'Americas', 'simon-johnson'),

('Anton Dibowitz', 'President and Chief Executive Officer', 'Valaris Limited', 'NYSE: VAL', 'Anton Dibowitz became the President and Chief Executive Officer of Valaris in December 2021, following his service as the interim President and CEO since September 2021. Prior to Valaris, he served as Chief Executive Officer of Seadrill Ltd. from July 2017 until October 2020, and as an advisor of Seadrill from November 2020 until March 2021. He previously served as Executive Vice President of Seadrill Management from June 2016, and as Chief Commercial Officer from January 2013. Dibowitz has over 20 years of drilling industry experience. Under his leadership, Valaris emerged from Chapter 11 bankruptcy and has focused on operational excellence, customer service, and shareholder returns.', 'Americas', 'anton-dibowitz'),

('John W. Lindsay', 'Chief Executive Officer', 'Helmerich & Payne, Inc.', 'NYSE: HP', 'John W. Lindsay has served as President and Chief Executive Officer of Helmerich & Payne (H&P) since March 2014 and has been a Director since September 2012. He began his career with H&P in 1987 as a drilling engineer and has held a variety of positions within the company in operations, management, and leadership. Lindsay earned his bachelor''s degree in Petroleum Engineering from The University of Tulsa (1984-1986). Before joining the oil and gas industry, he graduated with a degree in computer science but quickly realized that wasn''t his calling. He returned to school for petroleum engineering and started at H&P as a roughneck. Lindsay is committed to H&P''s values of ''Challenging Spirit, Flexibility, and Sincerity'' and emphasizes the importance of innovation, service attitude, and actively caring for employees.', 'Americas', 'john-lindsay'),

('Carey Ford', 'President and Chief Executive Officer', 'Precision Drilling Corp.', 'TSX: PD, NYSE: PDS', 'Carey Ford was appointed President and Chief Executive Officer of Precision Drilling Corporation in October 2025 as part of the company''s long-standing succession planning process. He succeeds Kevin Neveu, who served as President and CEO since 2007 and retired after 18 years with the company. Ford joined Precision in 2011 and has served as Chief Financial Officer since 2016, guiding the company''s financial strategy and strengthening investor confidence through several industry cycles. He has led all finance, capital markets, and corporate development activities and multiple operational support functions, giving him a deep understanding of Precision''s business and global operations. Ford has been supported by key leadership appointments including Gene Stahl as Chief Operating Officer and Dustin Honing as Chief Financial Officer.', 'Americas', 'carey-ford'),

('Clay Magouyrk & Mike Sicilia', 'Co-Chief Executive Officers', 'Oracle Corporation', 'NYSE: ORCL', 'Oracle appointed Clay Magouyrk and Mike Sicilia as co-CEOs in September 2025. Magouyrk, President of Cloud Infrastructure, was instrumental in developing the Gen2 platform, while Sicilia, President of Industries, managed Oracle''s applications tailored for various industries including banking and retail. Safra Catz, who served as CEO since 2014, transitioned to the role of Executive Vice Chair on the board. Larry Ellison continues to serve as Chairman of Oracle''s board and Chief Technology Officer. The appointments reflect Oracle''s transformation into an AI-driven cloud infrastructure company. Oracle announced the leadership transition under the banner ''AI Changes Everything,'' signaling its ongoing shift toward AI and cloud computing dominance.', 'Americas', 'clay-magouyrk-mike-sicilia'),

-- EUROPE (11)
('Paolo Rocca', 'Chairman and Chief Executive Officer', 'Tenaris S.A.', 'BIT: TEN, NYSE: TS, BMV: TS', 'Paolo Rocca is Chairman and CEO of Tenaris, positions he has held since 2002. He is the grandson of Agostino Rocca, founder of the Techint Group. Born in Milan, Italy in 1952, he earned a degree in political science from the Università degli Studi di Milano and attended the PMD at Harvard Business School in 1985. After serving as an assistant to the executive director of the World Bank, he began his career at Techint Group in 1985 as assistant to the chairman. He assumed as executive vice-president of Siderca in 1990. Rocca is also chairman of the board of directors of Ternium and is a member of the executive committee of the World Steel Association. As of July 2024, Forbes estimated his net worth at US$5.0 billion.', 'Europe', 'paolo-rocca'),

('Philippe Guillemot', 'Chairman of the Board and Chief Executive Officer', 'Vallourec S.A.', 'Euronext Paris: VK', 'Philippe Guillemot was appointed Chairman and Chief Executive Officer of Vallourec in March 2022. Born on May 6, 1959, he is a French national with extensive executive experience. Before joining Vallourec, he served as CEO at Elior Group (2017-2022), one of the world''s leading operators in contract catering and support services. His previous experience includes Chief Operating Officer at Alcatel-Lucent (2013-2016), where he drew up a business recovery and transformation plan; CEO and Board member of Europcar (2010-2012); and Chairman and CEO of Areva Transmission and Distribution (2004-2010). He was also a member of the Executive Committee at automotive supplier Faurecia (2001-2003) and Valeo (1998-2000). Guillemot has led Vallourec''s ''New Vallourec'' transformation plan focused on operational efficiency and organizational agility.', 'Europe', 'philippe-guillemot'),

('Igor Korytko', 'Management Board/General Director', 'TMK (OAO TMK)', 'Moscow Exchange: TRMK', 'Following the exit of founder Dmitry Pumpyansky in March 2022 due to EU sanctions related to the Russo-Ukrainian War, TMK''s management team took over control of the Russian pipe manufacturer. TMK CEO Igor Korytko, along with deputy CEO for economics and finance Tigran Petrosyan, first deputy CEO for special projects Vyacheslav Popkov, TMK vice president Andrei Kaplunov, and Marina Kerch (former head of finance department) became shareholders of Cyprus-based TMK Steel Holding Ltd, which owns 90.6% of TMK. The company is a leading global manufacturer and supplier of steel pipes for the oil and gas industry, with production assets in Russia, Kazakhstan, Romania and Czech Republic.', 'Europe', 'igor-korytko'),

('Géraldine Picaud', 'Chief Executive Officer', 'SGS S.A.', 'SIX Swiss Exchange: SGSN', 'Géraldine Picaud was appointed Chief Executive Officer of SGS in March 2024, succeeding Frankie Ng who stepped down after nine years. She joined SGS on December 1, 2023, initially leading Finance, Digital and Strategic Transformation, M&A, IT and Procurement. Prior to SGS, she was Group Chief Financial Officer and member of the Executive Committee at Holcim, a global leader in building solutions, and previously served as Group CFO and Executive Committee member at Essilor International, the world leader in eye care. She is currently a non-executive director and chairwoman of the Audit Committee at Danone. Picaud brings over 25 years of experience in senior management positions, delivering results and driving transformation.', 'Europe', 'geraldine-picaud'),

('Hinda Gharbi', 'Chief Executive Officer', 'Bureau Veritas S.A.', 'Euronext Paris: BVI', 'Hinda Gharbi was appointed Chief Executive Officer of Bureau Veritas on June 22, 2023, succeeding Didier Michaud-Daniel who led the company since March 2012. She joined Bureau Veritas as Chief Operating Officer and member of the group executive committee on May 1, 2022, and became Deputy Chief Executive Officer on January 1, 2023. Prior to Bureau Veritas, Gharbi brought extensive international experience, technical and technological expertise, and strong customer and people focus. She is believed to be the first woman to lead a member of the International Association of Classification Societies (IACS) business. Her appointment followed a comprehensive succession plan designed by the board of directors.', 'Europe', 'hinda-gharbi'),

('André Lacroix', 'Chief Executive Officer', 'Intertek Group plc', 'London Stock Exchange: ITRK', 'André Lacroix was appointed to the Intertek Board as Chief Executive Officer in May 2015. He is an experienced Chief Executive with a strong track record of delivering long-term growth strategies and shareholder value with global companies across diverse territories. Lacroix was previously Group Chief Executive of Inchcape plc from 2005 to 2015, during which time he strengthened its position in the global automotive market with a track record of delivering double-digit earnings growth. Prior to this, he was Chairman and Chief Executive Officer of Euro Disney S.C.A. From 1996 to 2003, he was President of Burger King International. He was formerly the Senior Independent Non-Executive Director of Reckitt Benckiser Group plc from October 2008 to December 2018. Lacroix holds an MBA from Rouen Business School.', 'Europe', 'andre-lacroix'),

('Aditya Mittal', 'Chief Executive Officer', 'ArcelorMittal S.A.', 'Euronext Amsterdam: MT', 'Aditya Mittal (born January 22, 1976) is the CEO of ArcelorMittal, the world''s leading steel company founded by his father Lakshmi Mittal. Born in India and raised in Indonesia, Mittal attended high school at Jakarta International School. He earned a bachelor''s degree in economics from the Wharton School of the University of Pennsylvania in 1996. He worked briefly at Credit Suisse First Boston before joining the family business in 1997. He was appointed Head of Mergers and Acquisitions in 1999 and led Mittal Steel''s offer for Arcelor that resulted in the 2006 merger creating ArcelorMittal. He was appointed CEO in February 2021, succeeding his father. Mittal is on the boards of ArcelorMittal, Aperam, Iconiq Capital, and is a trustee at Brookings Institution. He lives in London.', 'Europe', 'aditya-mittal'),

('Board of Directors', 'Leadership in Transition', 'Evraz plc', 'Moscow Exchange: EVRAZ', 'Evraz CEO Alexei Ivanov resigned in July 2022 after the UK imposed sanctions on the company and its largest shareholder Roman Abramovich in March 2022. Ivanov, who worked at Evraz since 2002, was appointed CEO in May 2021 after Alexander Frolov stepped down. Following the sanctions, all nonexecutive directors left the company''s board. Evraz''s management is now carried out by the company''s board of directors. The board currently has directors including Ruslan Ibragimov (vice president for corporate and legal issues at MTS) and independent director Andrei Loboda (managing partner of law firm Loboda, Filimonov & Partners). In July 2025, Atlas Holdings completed the acquisition of EVRAZ North America, forming Orion Steel Companies with Doug Matthews as CEO.', 'Europe', 'evraz-board'),

('Vincent Clerc', 'Chief Executive Officer', 'A.P. Moller – Maersk A/S', 'Nasdaq Copenhagen: MAERSK A, MAERSK B', 'Vincent Clerc was appointed CEO of A.P. Moller - Maersk effective January 1, 2023, succeeding Søren Skou who retired after leading the company''s transformation since 2016. Clerc joined Maersk in 1998 and has held several leadership positions in the USA and Denmark. Most recently, he was CEO of Ocean & Logistics (2019-2022), leading the enterprise-wide transformation to become the integrator of container logistics, and Chief Commercial Officer (2015-2019). Under his leadership, Maersk has focused on navigating shifting geopolitical circumstances, ensuring steady supply chains, and delivering record-high customer satisfaction. He holds an MBA from Columbia Business School and London Business School. Clerc resides in Copenhagen.', 'Europe', 'vincent-clerc'),

('Rolf Habben Jansen', 'Chief Executive Officer', 'Hapag-Lloyd AG', 'Frankfurt (XETRA): HLAG', 'Rolf Habben Jansen has been CEO of Hapag-Lloyd AG since July 2014 and a member of the Executive Board since April 2014. After graduating from Erasmus University Rotterdam in 1991, he worked in logistics for over 25 years, first with Royal Nedlloyd (later acquired by Danzas and merged into DHL) and then in the A.P. Moller Group, where he led Damco for five years beginning in 2009. Under his leadership, Hapag-Lloyd has continuously evolved strategically, significantly internationalized the company, and maintained a growth course. His contract was extended in 2024 for five years until March 31, 2029. The Supervisory Board cited his excellent performance over almost a decade and his success in navigating the company through challenging market conditions.', 'Europe', 'rolf-habben-jansen'),

('Christian Klein', 'Chief Executive Officer', 'SAP SE', 'Frankfurt (XETRA): SAP, NYSE: SAP', 'Christian Klein is Chief Executive Officer and chairman of the Executive Board of SAP SE. Born in 1980, Klein joined SAP in 1999 as a student and has held various positions within the company including Chief Financial Officer of SAP SuccessFactors, Chief Controlling Officer, and Chief Operating Officer (2016-2021). He was appointed to the Executive Board in 2018 as head of the Intelligent Enterprise Group. In October 2019, he was named Co-CEO together with Jennifer Morgan, before being appointed sole CEO on April 20, 2020. Under Klein''s leadership, SAP has accelerated its transformation into a cloud-first enterprise, with cloud revenue accounting for over half of total revenue. He holds a diploma in International Business Administration from the University of Cooperative Education in Mannheim, Germany.', 'Europe', 'christian-klein'),

-- ASIA-PACIFIC (7)
('Yoshihisa Kitano', 'President and Chief Executive Officer', 'JFE Holdings, Inc.', 'Tokyo Stock Exchange: 5411', 'Yoshihisa Kitano is CEO and President of JFE Holdings, Inc., appointed on April 1, 2024, and also serves as Chairman. He previously served as President and Chief Executive Officer at JFE Steel Corporation. Kitano (born 1958, age 67) has extensive experience in the steel industry and has been instrumental in advancing JFE''s vision of ''Contributing to society with the world''s most innovative technology.'' Under his leadership, JFE has focused on securing high-quality human resources, transforming corporate culture to encourage employees to work actively and take on challenges, embracing diversity and inclusion, and promoting carbon neutrality and a circular economy worldwide. JFE comprises three main global pillars: JFE Steel, JFE Engineering, and JFE Shoji.', 'Asia-Pacific', 'yoshihisa-kitano'),

('Eiji Hashimoto', 'Chairman and Chief Executive Officer', 'Nippon Steel Corporation', 'Tokyo Stock Exchange: 5401', 'Eiji Hashimoto (born 1954, age 70) has been President, CEO and Representative Director at Nippon Steel Corporation since April 2019. Effective April 1, 2024, he assumed the additional roles of Chairman while Tadashi Imai became President and Chief Operating Officer. Hashimoto took on these additional titles to ensure continuity in leadership during Nippon Steel''s $14.9 billion acquisition of U.S. Steel, which has faced significant opposition from the United Steelworkers union and U.S. lawmakers. Since taking office, Hashimoto has implemented significant restructuring measures, including closing several domestic facilities, and has made substantial international investments, acquiring steel companies in Thailand and securing interests in Canadian mining operations. He has also revised negotiation approaches with key clients like Toyota Motor to allow for quicker pricing adjustments.', 'Asia-Pacific', 'eiji-hashimoto'),

('Shingo Ueno', 'President and Chief Executive Officer', 'Sumitomo Corporation', 'Tokyo Stock Exchange: 8053', 'Shingo Ueno (born 1958, age 66) was appointed President and CEO of Sumitomo Corporation in April 2024. He previously served as Executive Vice President at Sumitomo Corporation from 2021 to 2023, where he was Head of Energy Innovation Initiative overseeing the Metal Products Business Unit and Mineral Resources, Energy. Ueno brings extensive international experience and expertise in the resources and energy sectors. Sumitomo Corporation is one of Japan''s major general trading companies (sogo shosha) with diverse business operations spanning metals, machinery, chemicals, energy, and more, operating globally across numerous industries.', 'Asia-Pacific', 'shingo-ueno'),

('Lee Hee-geun', 'CEO and President', 'POSCO (Pohang Iron & Steel Company)', 'Korea Exchange: 005490, NYSE: PKX', 'Lee Hee-geun was appointed CEO and President of POSCO in December 2024, effective after shareholder approval. He was promoted from head of POSCO''s Facility Reinforcement TF and will lead the company''s flagship steelmaking subsidiary. The appointment is part of POSCO Group Chairman Chang In-hwa''s first major personnel shake-up since taking office in March 2024. Lee replaces the previous CEO who served for less than a year. The leadership changes aim to streamline the organization, accelerate decision-making, and introduce a new generation of leaders to address uncertain market conditions. POSCO Group Chairman Chang In-hwa serves as Group CEO & Representative Director of POSCO Holdings.', 'Asia-Pacific', 'lee-hee-geun'),

('Gautam Malhotra', 'Chief Executive Officer', 'Jindal Steel Ltd.', 'BSE: 532286, NSE: JINDALSTEL', 'Gautam Malhotra was appointed Chief Executive Officer of Jindal Steel Ltd., effective October 28, 2025, marking the company''s first CEO appointment in five years. Malhotra joined the company in May 2024 and was elevated to CEO following his service on the Supervisory Advisory Board (SAB). With over two decades of multifaceted experience across strategy, operations, M&A, and digital transformation, he has played a key role in reshaping traditional industries through innovation and organizational agility. At Jindal Steel, he worked closely with leadership across mining, production, HR, logistics, and technology, driving the adoption of AI, Lean Six Sigma, TPM, and TQM methodologies. He also serves as a Strategic Advisor to FuelBuddy and Finocial Information Systems LLP, with expertise spanning India, Africa, and the Middle East. Naveen Jindal serves as Chairman of Jindal Steel.', 'Asia-Pacific', 'gautam-malhotra'),

('Wu Yu', 'Executive Director and Managing Director', 'COSCO Shipping Ports Ltd.', 'HKEX: 1199', 'Wu Yu was appointed Executive Director and Managing Director of COSCO SHIPPING Ports, effective April 2025. She also serves as Chair of the Risk Control Committee and member of key board committees including Executive, Remuneration, Nomination, and Investment & Strategic Planning. Wu replaces Zhu Tao as Managing Director, while Zhu remains Chairman of the Board. Wu brings over 25 years of experience in container shipping and digital transformation, having held senior leadership positions at COSCO SHIPPING Lines and OOCL. Her cross-sector perspective spans shipping, terminals, logistics, and IT, underscoring the company''s focus on integrated port-container synergies. She is also among the few female executives in China''s state-owned maritime sector, reflecting progress in ESG and gender diversity.', 'Asia-Pacific', 'wu-yu'),

('Wan Min', 'Chairman', 'COSCO Shipping Holdings Co. Ltd.', 'HKEX: 1919', 'Wan Min has served in various leadership positions at COSCO and COSCO SHIPPING. He previously served as Vice President of COSCO Container Lines Co., Ltd., President of COSCO Americas Inc., President of COSCO Container Lines Co., Ltd., Executive Vice President of COSCO, Director of the Board and President of COSCO SHIPPING, and Chairman of China Tourism Group Co., Ltd.. Wan Min has extensive experience in the global shipping industry and container logistics. COSCO Shipping is one of the world''s largest shipping companies, operating container ships, bulk carriers, and tankers worldwide.', 'Asia-Pacific', 'wan-min'),

-- AUSTRALIA (1)
('Tania Archibald', 'Managing Director and Chief Executive Officer', 'BlueScope Steel Limited', 'ASX: BSL', 'Tania Archibald was appointed Managing Director and Chief Executive Officer of BlueScope Steel, effective February 1, 2026, succeeding Mark Vassella who retired after eight years at the helm. Archibald, who is currently Chief Executive of BlueScope''s Australian Steel Products business (since 2023), has demonstrated outstanding leadership over her 30-year career at BlueScope. She previously served as Chief Financial Officer and held leadership roles in finance, strategy and business development across Australia, New Zealand, Vietnam and Indonesia. Her appointment followed a comprehensive global search by the board. BlueScope Chair Jane McAloon noted that Archibald is passionate about safety performance and wellbeing of people, committed to delivering for customers, and has a strong track record in driving sustainability, financial resilience and operational excellence. She will be based at BlueScope''s Melbourne head office.', 'Australia', 'tania-archibald');